//go:build ignore

package main

import (
	"fmt"
	"os"
	"time"

	"github.com/shinro/promql-transpiler/pkg/clickhouse"
	"github.com/shinro/promql-transpiler/pkg/transpiler"
)

// ═══════════════════════════════════════════════════════════════════════════════
// 1000-QUERY EXHAUSTIVE PROMQL TEST
// Covers every feature from the simplest to the most complex edge case.
// ═══════════════════════════════════════════════════════════════════════════════

func main() {
	queries := []struct {
		name   string
		promql string
	}{
		// ═══════════════════════════════════════════════════════════════
		// SECTION 1: BARE SELECTORS (1-30)
		// ═══════════════════════════════════════════════════════════════
		{"bare metric name", `up`},
		{"metric with underscore", `http_requests_total`},
		{"metric with colon", `namespace:http_requests:rate5m`},
		{"metric with digits", `node_cpu_seconds_total`},
		{"single eq matcher", `up{job="prometheus"}`},
		{"single neq matcher", `up{job!="test"}`},
		{"single regex matcher", `up{job=~"prom.*"}`},
		{"single neg-regex matcher", `up{job!~"test.*"}`},
		{"two matchers", `http_requests_total{job="api",status="200"}`},
		{"three matchers", `http_requests_total{job="api",method="GET",status="200"}`},
		{"four matchers mixed", `http_requests_total{job="api",status!="500",method=~"GET|POST",path!~"/health.*"}`},
		{"__name__ as matcher", `{__name__="up"}`},
		{"__name__ regex", `{__name__=~"http_.*"}`},
		{"__name__ with extra matcher", `{__name__="up",job="node"}`},
		{"empty metric with regex", `{job=~".+"}`},
		{"metric with long label value", `http_requests_total{path="/api/v1/query_range/long/path/segment"}`},
		{"metric with special chars in value", `http_requests_total{path="/api?foo=bar&baz=qux"}`},
		{"metric with escaped quotes", `http_requests_total{msg="it is a \"test\""}`},
		{"metric with empty label value", `up{env=""}`},
		{"metric with many labels", `m{a="1",b="2",c="3",d="4",e="5"}`},
		{"single letter metric", `x`},
		{"metric with leading underscore", `_internal_metric`},
		{"metric starting with digit-ish", `go_goroutines`},
		{"metric all lowercase", `process_cpu_seconds_total`},
		{"colon-separated metric", `job:request_errors:rate5m`},
		{"metric double colon", `ns:sub:metric`},
		{"metric dot-like with underscores", `api_server_request_duration_seconds`},
		{"deeply nested label path value", `http{handler="/api/v2/users/{id}/posts"}`},
		{"label with pipe in regex", `m{status=~"2..|3.."}`},
		{"label negated pipe regex", `m{code!~"4..|5.."}`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 2: RANGE VECTORS & MODIFIERS (31-60)
		// ═══════════════════════════════════════════════════════════════
		{"range 1s", `http_requests_total[1s]`},
		{"range 5m", `http_requests_total[5m]`},
		{"range 1h", `http_requests_total[1h]`},
		{"range 1d", `http_requests_total[1d]`},
		{"range 1w", `http_requests_total[1w]`},
		{"range 30s", `http_requests_total[30s]`},
		{"range 15m", `http_requests_total[15m]`},
		{"range 2h", `http_requests_total[2h]`},
		{"range 7d", `http_requests_total[7d]`},
		{"range with labels", `http_requests_total{job="api"}[5m]`},
		{"range with multi labels", `http_requests_total{job="api",status="200"}[5m]`},
		{"range with regex labels", `http_requests_total{method=~"GET|POST"}[5m]`},
		{"offset 5m", `http_requests_total offset 5m`},
		{"offset 1h", `http_requests_total offset 1h`},
		{"offset 1d", `http_requests_total offset 1d`},
		{"offset 1w", `up offset 1w`},
		{"range + offset", `http_requests_total[5m] offset 1h`},
		{"range + offset labels", `http_requests_total{job="api"}[5m] offset 1h`},
		{"range + large offset", `http_requests_total[5m] offset 7d`},
		{"@ modifier", `http_requests_total @ 1700000000`},
		{"@ modifier float", `http_requests_total @ 1700000000.5`},
		{"range + @", `http_requests_total[5m] @ 1700000000`},
		{"@ then offset", `http_requests_total[5m] @ 1700000000 offset 1h`},
		{"offset then @", `http_requests_total[5m] offset 1h @ 1700000000`},
		{"@ with labels", `http_requests_total{job="api"} @ 1700000000`},
		{"range + @ + labels", `http_requests_total{job="api"}[1h] @ 1700000000`},
		{"range + offset + @ + labels", `http_requests_total{job="api"}[5m] offset 1d @ 1700000000`},
		{"range 5m with complex labels", `http_requests_total{job=~"api.*",status!="500",method=~"GET|POST"}[5m]`},
		{"range + @ with int", `m[10m] @ 1609459200`},
		{"range + offset small", `m[1m] offset 30s`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 3: RATE FAMILY (61-100)
		// ═══════════════════════════════════════════════════════════════
		{"rate basic", `rate(http_requests_total[5m])`},
		{"rate with labels", `rate(http_requests_total{job="api"}[5m])`},
		{"rate regex labels", `rate(http_requests_total{status=~"2.."}[5m])`},
		{"rate with offset", `rate(http_requests_total[5m] offset 1h)`},
		{"rate with @", `rate(http_requests_total[5m] @ 1700000000)`},
		{"rate with offset and @", `rate(http_requests_total[5m] offset 1d @ 1700000000)`},
		{"rate 1m", `rate(http_requests_total[1m])`},
		{"rate 15m", `rate(http_requests_total[15m])`},
		{"rate 1h", `rate(http_requests_total[1h])`},
		{"rate 1d", `rate(http_requests_total[1d])`},
		{"irate basic", `irate(http_requests_total[5m])`},
		{"irate with labels", `irate(http_requests_total{job="api"}[5m])`},
		{"irate with offset", `irate(http_requests_total[5m] offset 1h)`},
		{"increase basic", `increase(http_requests_total[1h])`},
		{"increase with labels", `increase(http_requests_total{job="api"}[1h])`},
		{"increase with offset", `increase(http_requests_total[1h] offset 2h)`},
		{"increase 5m", `increase(http_requests_total[5m])`},
		{"increase 1d", `increase(http_requests_total[1d])`},
		{"delta basic", `delta(temperature[1h])`},
		{"delta with labels", `delta(temperature{env="prod"}[1h])`},
		{"delta with offset", `delta(temperature[1h] offset 2h)`},
		{"delta 5m", `delta(temperature[5m])`},
		{"delta 1d", `delta(temperature[1d])`},
		{"idelta basic", `idelta(temperature[5m])`},
		{"idelta with labels", `idelta(temperature{env="prod"}[5m])`},
		{"idelta with offset", `idelta(temperature[5m] offset 1h)`},
		{"rate of subquery", `rate(max_over_time(process_open_fds[1h])[10m:1m])`},
		{"rate with complex labels", `rate(http_requests_total{job="api",status=~"2..",method!~"OPTIONS"}[5m] offset 1h)`},
		{"increase with complex labels", `increase(http_requests_total{job=~"api|web",env="prod"}[1h])`},
		{"irate 1m window", `irate(http_requests_total{job="api"}[1m])`},
		{"delta with @ modifier", `delta(temperature[1h] @ 1700000000)`},
		{"increase with @ modifier", `increase(http_requests_total[1h] @ 1700000000)`},
		{"rate nested in another rate", `rate(http_requests_total[5m])`},
		{"rate of neg regex", `rate(http_requests_total{job!~"test.*"}[5m])`},
		{"rate multiple labels", `rate(m{a="1",b="2",c="3"}[5m])`},
		{"irate offset and @", `irate(m[5m] offset 1h @ 1700000000)`},
		{"increase 2h", `increase(m[2h])`},
		{"delta 30m", `delta(m[30m])`},
		{"idelta 1m", `idelta(m[1m])`},
		{"rate 30s", `rate(m[30s])`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 4: AGGREGATIONS (101-180)
		// ═══════════════════════════════════════════════════════════════
		{"sum bare", `sum(up)`},
		{"sum of rate", `sum(rate(http_requests_total[5m]))`},
		{"sum by 1 label", `sum by (job) (rate(http_requests_total[5m]))`},
		{"sum by 2 labels", `sum by (job, status) (rate(http_requests_total[5m]))`},
		{"sum by 3 labels", `sum by (job, status, method) (rate(http_requests_total[5m]))`},
		{"sum without 1 label", `sum without (instance) (rate(http_requests_total[5m]))`},
		{"sum without 2 labels", `sum without (instance, pod) (rate(http_requests_total[5m]))`},
		{"sum post-grouping", `sum(rate(http_requests_total[5m])) by (job)`},
		{"sum post-grouping 2 labels", `sum(rate(http_requests_total[5m])) by (job, status)`},
		{"avg bare", `avg(up)`},
		{"avg by", `avg by (cluster) (node_cpu_seconds_total)`},
		{"avg without", `avg without (instance) (node_cpu_seconds_total)`},
		{"min bare", `min(up)`},
		{"min by", `min by (job) (up)`},
		{"max bare", `max(up)`},
		{"max by", `max by (instance) (node_memory_MemFree_bytes)`},
		{"max without", `max without (pod) (container_memory_usage_bytes)`},
		{"count bare", `count(up)`},
		{"count by", `count by (status) (http_requests_total)`},
		{"count without", `count without (instance) (http_requests_total)`},
		{"stddev bare", `stddev(rate(http_requests_total[5m]))`},
		{"stddev by", `stddev by (job) (rate(http_requests_total[5m]))`},
		{"stdvar bare", `stdvar(rate(http_requests_total[5m]))`},
		{"stdvar by", `stdvar by (job) (rate(http_requests_total[5m]))`},
		{"topk 3", `topk(3, rate(http_requests_total[5m]))`},
		{"topk 5", `topk(5, up)`},
		{"topk 10", `topk(10, rate(http_requests_total[5m]))`},
		{"bottomk 3", `bottomk(3, up)`},
		{"bottomk 5", `bottomk(5, rate(http_requests_total[5m]))`},
		{"bottomk 10", `bottomk(10, up)`},
		{"quantile 0.5", `quantile(0.5, rate(http_requests_total[5m]))`},
		{"quantile 0.9", `quantile(0.9, rate(http_requests_total[5m]))`},
		{"quantile 0.95", `quantile(0.95, rate(http_requests_total[5m]))`},
		{"quantile 0.99", `quantile(0.99, rate(http_requests_total[5m]))`},
		{"quantile by", `quantile by (job) (0.99, rate(http_requests_total[5m]))`},
		{"count_values", `count_values("version", build_info)`},
		{"count_values of up", `count_values("status", up)`},
		{"group bare", `group(up)`},
		{"group by", `group by (job) (up)`},
		{"group without", `group without (instance) (up)`},
		{"sum of increase", `sum(increase(http_requests_total[1h]))`},
		{"avg of delta", `avg(delta(temperature[1h]))`},
		{"max of rate", `max(rate(http_requests_total[5m]))`},
		{"min of rate", `min(rate(http_requests_total[5m]))`},
		{"count of rate", `count(rate(http_requests_total[5m]))`},
		{"topk of sum", `topk(5, sum by (job) (rate(http_requests_total[5m])))`},
		{"bottomk of avg", `bottomk(3, avg by (job) (up))`},
		{"sum of sum", `sum(sum by (job) (rate(http_requests_total[5m])))`},
		{"max of sum", `max(sum by (job) (rate(http_requests_total[5m])))`},
		{"avg of max", `avg(max by (job) (rate(http_requests_total[5m])))`},
		{"3-level agg", `max(avg by (cluster) (sum by (cluster, job) (rate(http_requests_total[5m]))))`},
		{"sum with complex inner", `sum by (path, method) (rate(http_requests_total{status=~"5.."}[5m]))`},
		{"sum of irate", `sum(irate(http_requests_total[5m]))`},
		{"count of count_values", `count(count_values("v", build_info))`},
		{"sum without post-grouping", `sum(rate(http_requests_total[5m])) without (instance)`},
		{"topk of topk", `topk(3, topk(10, rate(http_requests_total[5m])))`},
		{"quantile of rate with labels", `quantile(0.95, rate(http_requests_total{job="api"}[5m]))`},
		{"sum of vector", `sum(vector(1))`},
		{"count of up filtered", `count(up{job=~"node.*"})`},
		{"sum by with offset", `sum by (job) (rate(http_requests_total[5m] offset 1h))`},
		{"avg by with @", `avg by (job) (rate(http_requests_total[5m] @ 1700000000))`},
		{"max by with regex filter", `max by (instance) (rate(http_requests_total{status=~"2.."}[5m]))`},
		{"sum of absent", `sum(absent(nonexistent{job="x"}))`},
		{"stddev of sum", `stddev(sum by (job) (rate(http_requests_total[5m])))`},
		{"sum by with increase", `sum by (job) (increase(http_requests_total[1h]))`},
		{"min of max", `min(max by (job) (up))`},
		{"count_values of rate", `count_values("bucket", rate(http_requests_total[5m]))`},
		{"sum of scalar", `sum(vector(42))`},
		{"avg of increase", `avg by (job) (increase(http_requests_total[1h]))`},
		{"sum of changes", `sum(changes(process_start_time_seconds[1h]))`},
		{"topk 1", `topk(1, rate(http_requests_total[5m]))`},
		{"bottomk 1", `bottomk(1, up)`},
		{"quantile 0", `quantile(0, rate(http_requests_total[5m]))`},
		{"quantile 1", `quantile(1, rate(http_requests_total[5m]))`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 5: OVER-TIME FUNCTIONS (181-240)
		// ═══════════════════════════════════════════════════════════════
		{"avg_over_time", `avg_over_time(up[5m])`},
		{"avg_over_time labels", `avg_over_time(node_cpu_seconds_total{mode="idle"}[5m])`},
		{"avg_over_time offset", `avg_over_time(up[5m] offset 1h)`},
		{"avg_over_time 1h", `avg_over_time(up[1h])`},
		{"avg_over_time 1d", `avg_over_time(up[1d])`},
		{"sum_over_time", `sum_over_time(http_requests_total[1h])`},
		{"sum_over_time labels", `sum_over_time(http_requests_total{job="api"}[1h])`},
		{"sum_over_time offset", `sum_over_time(http_requests_total[1h] offset 2h)`},
		{"min_over_time", `min_over_time(temperature[30m])`},
		{"min_over_time labels", `min_over_time(temperature{env="prod"}[30m])`},
		{"max_over_time", `max_over_time(temperature[30m])`},
		{"max_over_time labels", `max_over_time(temperature{env="prod"}[30m])`},
		{"max_over_time offset", `max_over_time(temperature[30m] offset 1h)`},
		{"count_over_time", `count_over_time(up[5m])`},
		{"count_over_time labels", `count_over_time(up{job="node"}[5m])`},
		{"stddev_over_time", `stddev_over_time(temperature[1h])`},
		{"stdvar_over_time", `stdvar_over_time(temperature[1h])`},
		{"quantile_over_time 0.5", `quantile_over_time(0.5, temperature[1h])`},
		{"quantile_over_time 0.9", `quantile_over_time(0.9, temperature[1h])`},
		{"quantile_over_time 0.99", `quantile_over_time(0.99, temperature[1h])`},
		{"quantile_over_time labels", `quantile_over_time(0.95, http_requests_total{job="api"}[5m])`},
		{"quantile_over_time offset", `quantile_over_time(0.9, temperature[1h] offset 2h)`},
		{"last_over_time", `last_over_time(up[5m])`},
		{"last_over_time labels", `last_over_time(up{job="node"}[5m])`},
		{"present_over_time", `present_over_time(up[5m])`},
		{"present_over_time labels", `present_over_time(up{job="node"}[5m])`},
		{"absent_over_time", `absent_over_time(up[5m])`},
		{"absent_over_time labels", `absent_over_time(nonexistent{job="x"}[5m])`},
		{"avg_over_time with @", `avg_over_time(up[5m] @ 1700000000)`},
		{"sum_over_time 5m", `sum_over_time(m[5m])`},
		{"min_over_time 1h", `min_over_time(m[1h])`},
		{"max_over_time 1d", `max_over_time(m[1d])`},
		{"count_over_time 1h", `count_over_time(m[1h])`},
		// Over-time with subquery
		{"avg_over_time subquery", `avg_over_time(rate(http_requests_total[5m])[30m:1m])`},
		{"sum_over_time subquery", `sum_over_time(rate(http_requests_total[5m])[1h:5m])`},
		{"min_over_time subquery", `min_over_time(rate(http_requests_total[5m])[30m:1m])`},
		{"max_over_time subquery", `max_over_time(rate(http_requests_total[5m])[30m:1m])`},
		{"count_over_time subquery", `count_over_time(rate(http_requests_total[5m])[30m:1m])`},
		{"stddev_over_time subquery", `stddev_over_time(rate(m[5m])[1h:5m])`},
		{"stdvar_over_time subquery", `stdvar_over_time(rate(m[5m])[1h:5m])`},
		{"quantile_over_time subquery", `quantile_over_time(0.99, rate(m[5m])[1h:5m])`},
		// Over-time subquery with offset
		{"max_over_time subquery offset", `max_over_time(rate(m[5m])[1h:5m] offset 2h)`},
		{"avg_over_time subquery offset", `avg_over_time(rate(m[5m])[30m:1m] offset 1h)`},
		{"avg_over_time of sum subquery", `avg_over_time(sum(rate(m[5m]))[1h:5m])`},
		{"max_over_time of avg subquery", `max_over_time(avg by (job) (rate(m[5m]))[30m:1m])`},
		{"min_over_time subquery no step", `min_over_time(rate(m[5m])[30m:])`},
		{"max_over_time subquery no step", `max_over_time(rate(m[5m])[30m:])`},
		{"quantile_over_time of agg subquery", `quantile_over_time(0.9, sum by (job) (rate(m[5m]))[1h:5m])`},
		{"avg_over_time of delta subquery", `avg_over_time(delta(temperature[5m])[1h:5m])`},
		{"sum_over_time subquery @", `sum_over_time(rate(m[5m])[1h:5m] @ 1700000000)`},
		{"last_over_time complex labels", `last_over_time(http_requests_total{job="api",status=~"2.."}[5m])`},
		{"count_over_time complex labels", `count_over_time(http_requests_total{method!~"OPTIONS"}[1h])`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 6: MATH FUNCTIONS (241-300)
		// ═══════════════════════════════════════════════════════════════
		{"abs of metric", `abs(up)`},
		{"abs of delta", `abs(delta(temperature[1h]))`},
		{"abs of rate", `abs(rate(http_requests_total[5m]))`},
		{"abs of binary", `abs(rate(a[5m]) - rate(b[5m]))`},
		{"ceil of rate", `ceil(rate(http_requests_total[5m]))`},
		{"ceil of metric", `ceil(up)`},
		{"floor of rate", `floor(rate(http_requests_total[5m]))`},
		{"floor of metric", `floor(up)`},
		{"round basic", `round(rate(http_requests_total[5m]))`},
		{"round with precision", `round(rate(http_requests_total[5m]), 0.01)`},
		{"round precision 0.1", `round(up, 0.1)`},
		{"round precision 10", `round(up, 10)`},
		{"sqrt of rate", `sqrt(rate(http_requests_total[5m]))`},
		{"sqrt of metric", `sqrt(up)`},
		{"exp of metric", `exp(up)`},
		{"exp of rate", `exp(rate(m[5m]))`},
		{"ln of metric", `ln(up)`},
		{"ln of rate", `ln(rate(m[5m]))`},
		{"log2 of metric", `log2(up)`},
		{"log2 of rate", `log2(rate(m[5m]))`},
		{"log10 of metric", `log10(up)`},
		{"log10 of rate", `log10(rate(m[5m]))`},
		{"sgn of metric", `sgn(up)`},
		{"sgn of delta", `sgn(delta(temperature[1h]))`},
		{"clamp 0-100", `clamp(rate(http_requests_total[5m]), 0, 100)`},
		{"clamp 0-1", `clamp(up, 0, 1)`},
		{"clamp negative", `clamp(delta(m[1h]), -10, 10)`},
		{"clamp_min 0", `clamp_min(rate(http_requests_total[5m]), 0)`},
		{"clamp_min negative", `clamp_min(delta(m[1h]), -1)`},
		{"clamp_max 100", `clamp_max(rate(http_requests_total[5m]), 100)`},
		{"clamp_max 1", `clamp_max(up, 1)`},
		{"abs of sum", `abs(sum(rate(m[5m])))`},
		{"ceil of avg", `ceil(avg(rate(m[5m])))`},
		{"floor of max", `floor(max(rate(m[5m])))`},
		{"sqrt of sum", `sqrt(sum(rate(m[5m])))`},
		{"exp of sum", `exp(sum(rate(m[5m])))`},
		{"ln of avg", `ln(avg(up))`},
		{"log2 of max", `log2(max(up))`},
		{"log10 of min", `log10(min(up))`},
		{"clamp of sum", `clamp(sum by (job) (rate(m[5m])), 0, 1000)`},
		{"clamp_min of avg", `clamp_min(avg by (job) (rate(m[5m])), 0)`},
		{"clamp_max of topk", `clamp_max(topk(5, rate(m[5m])), 100)`},
		{"abs nested in ceil", `ceil(abs(delta(m[1h])))`},
		{"floor of sqrt", `floor(sqrt(rate(m[5m])))`},
		{"round of ln", `round(ln(rate(m[5m])))`},
		{"exp of ln identity", `exp(ln(up))`},
		{"sgn of sum", `sgn(sum(delta(m[1h])))`},
		{"abs of clamp", `abs(clamp(delta(m[1h]), -10, 10))`},
		{"sqrt of abs", `sqrt(abs(delta(m[1h])))`},
		{"ceil of clamp_min", `ceil(clamp_min(rate(m[5m]), 0))`},
		{"floor of clamp_max", `floor(clamp_max(rate(m[5m]), 100))`},
		{"abs of binary subtraction", `abs(rate(a[5m]) - rate(b[5m]))`},
		{"clamp of binary mul", `clamp(rate(m[5m]) * 100, 0, 10000)`},
		{"sgn of binary sub", `sgn(rate(a[5m]) - rate(b[5m]))`},
		{"round of binary div", `round(rate(a[5m]) / rate(b[5m]), 0.001)`},
		{"ln of increase", `ln(increase(m[1h]))`},
		{"log10 of increase", `log10(increase(m[1h]))`},
		{"exp of sgn", `exp(sgn(delta(m[1h])))`},
		{"sqrt of increase", `sqrt(increase(m[1h]))`},
		{"abs of idelta", `abs(idelta(m[5m]))`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 7: TRIGONOMETRIC FUNCTIONS (301-340)
		// ═══════════════════════════════════════════════════════════════
		{"sin of metric", `sin(up)`},
		{"cos of metric", `cos(up)`},
		{"tan of metric", `tan(up)`},
		{"asin of metric", `asin(up)`},
		{"acos of metric", `acos(up)`},
		{"atan of metric", `atan(up)`},
		{"sinh of metric", `sinh(up)`},
		{"cosh of metric", `cosh(up)`},
		{"tanh of metric", `tanh(up)`},
		{"asinh of metric", `asinh(up)`},
		{"acosh of metric", `acosh(up)`},
		{"atanh of metric", `atanh(up)`},
		{"deg of metric", `deg(up)`},
		{"rad of metric", `rad(up)`},
		{"pi()", `pi()`},
		{"sin of rate", `sin(rate(m[5m]))`},
		{"cos of rate", `cos(rate(m[5m]))`},
		{"tan of rate", `tan(rate(m[5m]))`},
		{"sin of sum", `sin(sum(rate(m[5m])))`},
		{"cos of avg", `cos(avg(up))`},
		{"deg of rad identity", `deg(rad(up))`},
		{"rad of deg identity", `rad(deg(up))`},
		{"sin of pi", `sin(pi())`},
		{"cos of pi", `cos(pi())`},
		{"sinh of rate", `sinh(rate(m[5m]))`},
		{"cosh of rate", `cosh(rate(m[5m]))`},
		{"tanh of rate", `tanh(rate(m[5m]))`},
		{"asinh of rate", `asinh(rate(m[5m]))`},
		{"acosh of rate", `acosh(rate(m[5m]))`},
		{"atanh of rate", `atanh(rate(m[5m]))`},
		{"sin of delta", `sin(delta(m[1h]))`},
		{"cos of delta", `cos(delta(m[1h]))`},
		{"tan squared", `tan(up) * tan(up)`},
		{"sin+cos identity check", `sin(up) * sin(up) + cos(up) * cos(up)`},
		{"asin of sin", `asin(sin(up))`},
		{"sinh of zero arg sum", `sinh(sum(up) * 0)`},
		{"tanh of sum", `tanh(sum by (job) (rate(m[5m])))`},
		{"deg of asin", `deg(asin(up))`},
		{"rad of atan", `rad(atan(up))`},
		{"sin of time", `sin(time())`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 8: DATE/TIME FUNCTIONS (341-380)
		// ═══════════════════════════════════════════════════════════════
		{"time()", `time()`},
		{"timestamp(up)", `timestamp(up)`},
		{"timestamp(rate)", `timestamp(rate(m[5m]))`},
		{"day_of_month()", `day_of_month()`},
		{"day_of_month(metric)", `day_of_month(process_start_time_seconds)`},
		{"day_of_week()", `day_of_week()`},
		{"day_of_week(metric)", `day_of_week(process_start_time_seconds)`},
		{"day_of_year()", `day_of_year()`},
		{"day_of_year(metric)", `day_of_year(process_start_time_seconds)`},
		{"days_in_month()", `days_in_month()`},
		{"days_in_month(metric)", `days_in_month(process_start_time_seconds)`},
		{"hour()", `hour()`},
		{"hour(metric)", `hour(process_start_time_seconds)`},
		{"minute()", `minute()`},
		{"minute(metric)", `minute(process_start_time_seconds)`},
		{"month()", `month()`},
		{"month(metric)", `month(process_start_time_seconds)`},
		{"year()", `year()`},
		{"year(metric)", `year(process_start_time_seconds)`},
		{"time() in binary", `time() - timestamp(up)`},
		{"time() in comparison", `time() - timestamp(up) > 300`},
		{"day_of_week in binary", `day_of_week() == 0 or day_of_week() == 6`},
		{"hour in comparison", `hour() >= 9 and hour() <= 17`},
		{"month in comparison", `month() == 12`},
		{"year in comparison", `year() >= 2024`},
		{"timestamp diff", `time() - timestamp(up) > 600`},
		{"day_of_month binary", `day_of_month() > 15`},
		{"days_in_month equality", `days_in_month() == 28`},
		{"hour filter", `hour() < 6`},
		{"minute filter", `minute() == 0`},
		{"day_of_year comparison", `day_of_year() > 180`},
		{"timestamp of rate", `timestamp(rate(m[5m]))`},
		{"time minus 3600", `time() - 3600`},
		{"day_of_month nested", `day_of_month() + 1`},
		{"hour() times 3600", `hour() * 3600`},
		{"minute() mod 15", `minute() % 15`},
		{"year() power", `year() ^ 0`},
		{"time() div 86400", `time() / 86400`},
		{"timestamp of sum", `timestamp(sum(up))`},
		{"time() minus timestamp", `time() - timestamp(up)`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 9: HISTOGRAM (381-410)
		// ═══════════════════════════════════════════════════════════════
		{"histogram_quantile p50", `histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"histogram_quantile p90", `histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"histogram_quantile p95", `histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"histogram_quantile p99", `histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"histogram_quantile p999", `histogram_quantile(0.999, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"histogram by le+job", `histogram_quantile(0.95, sum by (le, job) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"histogram by le+method", `histogram_quantile(0.95, sum by (le, method) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"histogram by le+path+method", `histogram_quantile(0.95, sum by (le, path, method) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"histogram with filter", `histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{job="api"}[5m])))`},
		{"histogram with regex filter", `histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{method=~"GET|POST"}[5m])))`},
		{"histogram with offset", `histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m] offset 1h)))`},
		{"histogram p50 vs p99 diff", `histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket[5m]))) - histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"histogram in comparison", `histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket[5m]))) > 1.0`},
		{"histogram in sort", `sort_desc(histogram_quantile(0.95, sum by (le, job) (rate(http_request_duration_seconds_bucket[5m]))))`},
		{"histogram with label_replace", `label_replace(histogram_quantile(0.99, sum by (le, job) (rate(http_request_duration_seconds_bucket[5m]))), "svc", "$1", "job", "(.*)")`},
		{"histogram irate", `histogram_quantile(0.95, sum by (le) (irate(http_request_duration_seconds_bucket[5m])))`},
		{"histogram increase", `histogram_quantile(0.95, sum by (le) (increase(http_request_duration_seconds_bucket[1h])))`},
		{"histogram complex filter", `histogram_quantile(0.99, sum by (le, method) (rate(http_request_duration_seconds_bucket{job="api",status!~"5.."}[5m])))`},
		{"histogram 0 quantile", `histogram_quantile(0, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"histogram 1 quantile", `histogram_quantile(1, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"histogram with @", `histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m] @ 1700000000)))`},
		{"histogram ratio", `histogram_quantile(0.95, sum by(le)(rate(a_bucket[5m]))) / histogram_quantile(0.95, sum by(le)(rate(b_bucket[5m])))`},
		{"histogram by le,cluster,region", `histogram_quantile(0.99, sum by (le, cluster, region) (rate(http_request_duration_seconds_bucket{env="prod"}[5m])))`},
		{"histogram in topk", `topk(5, histogram_quantile(0.95, sum by (le, job) (rate(http_request_duration_seconds_bucket[5m]))))`},
		{"histogram in avg", `avg(histogram_quantile(0.95, sum by (le, job) (rate(http_request_duration_seconds_bucket[5m]))))`},
		{"histogram in abs", `abs(histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket[5m]))) - 1)`},
		{"histogram with multi labels filter", `histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{job="api",env="prod",dc=~"us.*"}[5m])))`},
		{"histogram count sum inner", `histogram_quantile(0.95, sum by(le)(rate(bucket{a="1",b="2"}[5m])))`},
		{"histogram in clamp", `clamp(histogram_quantile(0.99, sum by(le)(rate(bucket[5m]))), 0, 10)`},
		{"histogram 30m rate", `histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[30m])))`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 10: LABEL FUNCTIONS (411-445)
		// ═══════════════════════════════════════════════════════════════
		{"label_replace basic", `label_replace(up, "host", "$1", "instance", "(.*):.*")`},
		{"label_replace job extract", `label_replace(up, "service", "$1", "job", "(.*)-service")`},
		{"label_replace empty src", `label_replace(up, "dc", "us-east", "", "")`},
		{"label_replace full capture", `label_replace(up, "copy", "$1", "job", "(.*)")`},
		{"label_replace complex regex", `label_replace(up, "ns", "$1", "instance", "([^:]+):.*")`},
		{"label_replace of rate", `label_replace(rate(m[5m]), "svc", "$1", "job", "(.*)")`},
		{"label_replace of sum", `label_replace(sum by (job) (rate(m[5m])), "svc", "$1", "job", "(.*)")`},
		{"label_replace of histogram", `label_replace(histogram_quantile(0.95, sum by (le, job) (rate(bucket[5m]))), "svc", "$1", "job", "(.*)")`},
		{"label_replace nested", `label_replace(label_replace(up, "a", "$1", "job", "(.*)"), "b", "$1", "instance", "(.*)")`},
		{"label_replace triple nested", `label_replace(label_replace(label_replace(up, "a", "$1", "job", "(.*)"), "b", "$1", "instance", "(.*)"), "c", "$1", "a", "(.*)")`},
		{"label_join basic", `label_join(up, "full_id", "-", "job", "instance")`},
		{"label_join 3 src", `label_join(up, "id", ":", "job", "instance", "env")`},
		{"label_join 4 src", `label_join(up, "id", "/", "a", "b", "c", "d")`},
		{"label_join comma sep", `label_join(up, "all", ",", "job", "instance")`},
		{"label_join empty sep", `label_join(up, "all", "", "job", "instance")`},
		{"label_join of rate", `label_join(rate(m[5m]), "id", "-", "job", "instance")`},
		{"label_join of sum", `label_join(sum by (job, instance) (rate(m[5m])), "id", ":", "job", "instance")`},
		{"label_join then label_replace", `label_replace(label_join(up, "full", "-", "job", "instance"), "svc", "$1", "full", "(.*)-.*")`},
		{"label_replace then label_join", `label_join(label_replace(up, "dc", "$1", "instance", "(.*)-.+"), "id", ":", "dc", "job")`},
		{"label_replace of topk", `label_replace(topk(5, rate(m[5m])), "svc", "$1", "job", "(.*)")`},
		{"label_join of bottomk", `label_join(bottomk(3, up), "id", "-", "job", "instance")`},
		{"label_replace of sort", `label_replace(sort_desc(rate(m[5m])), "x", "$1", "job", "(.*)")`},
		{"label_replace group1 group2", `label_replace(up, "result", "$1-$2", "instance", "([^:]+):(.*)")`},
		{"label_replace of avg", `label_replace(avg by (job) (up), "svc", "$1", "job", "(.*)")`},
		{"label_join of max", `label_join(max by (job, instance) (up), "uid", "/", "job", "instance")`},
		{"label_replace with vector matching", `label_replace(rate(m[5m]) / on(job) group_left(version) build_info, "svc", "$1", "job", "(.*)")`},
		{"label_join 5 src labels", `label_join(up, "mega", ".", "a", "b", "c", "d", "e")`},
		{"label_replace dollar sign", `label_replace(up, "new", "${1}_suffix", "job", "(.*)")`},
		{"label_replace in comparison", `label_replace(up, "svc", "$1", "job", "(.*)") > 0`},
		{"label_join in binary", `label_join(up, "id", "-", "job", "instance") + 0`},
		{"label_replace of increase", `label_replace(increase(m[1h]), "svc", "$1", "job", "(.*)")`},
		{"label_join in sort", `sort_desc(label_join(rate(m[5m]), "id", "-", "job", "instance"))`},
		{"label_replace multi capture", `label_replace(up, "out", "$1__$2", "instance", "(.+):(.+)")`},
		{"label_replace of absent", `label_replace(absent(nonexistent{job="x"}), "svc", "missing", "", "")`},
		{"label_join of vector", `label_join(vector(1), "id", "-", "job")`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 11: SORT, ABSENT, CHANGES, RESETS, DERIV, PREDICT, HOLT (446-500)
		// ═══════════════════════════════════════════════════════════════
		{"sort of rate", `sort(rate(http_requests_total[5m]))`},
		{"sort of metric", `sort(up)`},
		{"sort of sum", `sort(sum by (job) (rate(m[5m])))`},
		{"sort_desc of rate", `sort_desc(rate(http_requests_total[5m]))`},
		{"sort_desc of metric", `sort_desc(up)`},
		{"sort_desc of sum", `sort_desc(sum by (job) (rate(m[5m])))`},
		{"sort_desc of avg", `sort_desc(avg by (instance) (rate(m[5m])))`},
		{"absent basic", `absent(up{job="missing"})`},
		{"absent with labels", `absent(nonexistent{job="x",env="prod"})`},
		{"absent simple", `absent(up)`},
		{"changes basic", `changes(process_start_time_seconds[15m])`},
		{"changes 1h", `changes(process_start_time_seconds[1h])`},
		{"changes with labels", `changes(process_start_time_seconds{job="api"}[15m])`},
		{"changes with offset", `changes(process_start_time_seconds[15m] offset 1h)`},
		{"resets basic", `resets(process_start_time_seconds[15m])`},
		{"resets 1h", `resets(process_start_time_seconds[1h])`},
		{"resets with labels", `resets(process_start_time_seconds{job="api"}[15m])`},
		{"resets with offset", `resets(process_start_time_seconds[15m] offset 1h)`},
		{"deriv basic", `deriv(process_cpu_seconds_total[1h])`},
		{"deriv with labels", `deriv(process_cpu_seconds_total{job="api"}[1h])`},
		{"deriv with offset", `deriv(process_cpu_seconds_total[1h] offset 2h)`},
		{"deriv subquery", `deriv(rate(http_requests_total[5m])[1h:1m])`},
		{"deriv with @", `deriv(process_cpu_seconds_total[1h] @ 1700000000)`},
		{"predict_linear basic", `predict_linear(node_filesystem_free_bytes[1h], 3600)`},
		{"predict_linear 4h", `predict_linear(node_filesystem_free_bytes[4h], 86400)`},
		{"predict_linear with labels", `predict_linear(node_filesystem_free_bytes{env="prod"}[1h], 3600)`},
		{"predict_linear with offset", `predict_linear(node_filesystem_free_bytes[4h] offset 1h, 86400)`},
		{"predict_linear subquery", `predict_linear(avg_over_time(node_filesystem_free_bytes[30m])[2h:1m], 86400)`},
		{"predict_linear comparison", `predict_linear(node_filesystem_free_bytes[4h], 86400) < 0`},
		{"holt_winters basic", `holt_winters(process_resident_memory_bytes[1h], 0.5, 0.5)`},
		{"holt_winters with labels", `holt_winters(process_resident_memory_bytes{job="api"}[1h], 0.3, 0.7)`},
		{"holt_winters different params", `holt_winters(process_resident_memory_bytes[2h], 0.1, 0.9)`},
		{"scalar of metric", `scalar(up)`},
		{"scalar of sum", `scalar(sum(up))`},
		{"scalar of rate", `scalar(rate(m[5m]))`},
		{"vector 1", `vector(1)`},
		{"vector 0", `vector(0)`},
		{"vector 42", `vector(42)`},
		{"vector 3.14", `vector(3.14)`},
		{"vector in binary", `vector(1) + up`},
		{"sort of predict_linear", `sort_desc(predict_linear(node_filesystem_free_bytes[4h], 86400))`},
		{"changes in sum", `sum by (job) (changes(process_start_time_seconds[1h]))`},
		{"resets in max", `max by (instance) (resets(process_start_time_seconds[1h]))`},
		{"deriv in avg", `avg by (instance) (deriv(node_filesystem_free_bytes[1h]))`},
		{"absent in sum", `sum(absent(nonexistent{job="x"}))`},
		{"changes + resets", `changes(m[1h]) + resets(m[1h])`},
		{"scalar in binary", `scalar(sum(up)) * 100`},
		{"predict_linear in sort", `sort_desc(predict_linear(node_filesystem_free_bytes[4h], 86400))`},
		{"predict_linear in label_replace", `label_replace(predict_linear(node_filesystem_free_bytes[4h], 86400), "svc", "$1", "job", "(.*)")`},
		{"deriv of memory over 4h subquery", `deriv(avg_over_time(node_memory_MemAvailable_bytes[1h])[4h:1m])`},
		{"predict_linear subq comparison", `predict_linear(rate(node_cpu_seconds_total[1h])[4h:5m], 86400) > 0.9`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 12: BINARY OPERATIONS (501-560)
		// ═══════════════════════════════════════════════════════════════
		{"add scalar", `up + 1`},
		{"sub scalar", `up - 1`},
		{"mul scalar", `rate(m[5m]) * 100`},
		{"div scalar", `rate(m[5m]) / 1000`},
		{"mod scalar", `up % 2`},
		{"pow scalar", `up ^ 2`},
		{"scalar + metric", `1 + up`},
		{"scalar - metric", `100 - up`},
		{"scalar * metric", `100 * rate(m[5m])`},
		{"scalar / metric", `1 / rate(m[5m])`},
		{"metric + metric", `rate(a[5m]) + rate(b[5m])`},
		{"metric - metric", `rate(a[5m]) - rate(b[5m])`},
		{"metric * metric", `rate(a[5m]) * rate(b[5m])`},
		{"metric / metric", `rate(a[5m]) / rate(b[5m])`},
		{"metric % metric", `rate(a[5m]) % rate(b[5m])`},
		{"metric ^ metric", `rate(a[5m]) ^ rate(b[5m])`},
		{"gt scalar", `up > 0`},
		{"lt scalar", `up < 100`},
		{"eq scalar", `up == 1`},
		{"neq scalar", `up != 0`},
		{"gte scalar", `rate(m[5m]) >= 0.5`},
		{"lte scalar", `rate(m[5m]) <= 10`},
		{"gt metric", `rate(a[5m]) > rate(b[5m])`},
		{"lt metric", `rate(a[5m]) < rate(b[5m])`},
		{"eq metric", `rate(a[5m]) == rate(b[5m])`},
		{"neq metric", `rate(a[5m]) != rate(b[5m])`},
		{"bool gt", `up > bool 0`},
		{"bool lt", `up < bool 100`},
		{"bool eq", `up == bool 1`},
		{"bool neq", `up != bool 0`},
		{"bool gte", `rate(m[5m]) >= bool 0.5`},
		{"bool lte", `rate(m[5m]) <= bool 10`},
		{"chained add", `up + 1 + 2`},
		{"chained mul", `rate(m[5m]) * 100 * 0.01`},
		{"mixed precedence", `rate(a[5m]) + rate(b[5m]) * 2`},
		{"mixed precedence 2", `rate(a[5m]) * 2 + rate(b[5m])`},
		{"parens override precedence", `(rate(a[5m]) + rate(b[5m])) * 2`},
		{"complex arithmetic", `(rate(a[5m]) + rate(b[5m])) / (rate(c[5m]) + rate(d[5m]))`},
		{"power chain", `up ^ 2 ^ 3`},
		{"div and mod", `up / 3 + up % 3`},
		{"scalar scalar add", `1 + 2`},
		{"scalar scalar mul", `3 * 4`},
		{"scalar scalar div", `10 / 3`},
		{"scalar scalar pow", `2 ^ 10`},
		{"scalar scalar comparison", `1 > 0`},
		{"metric times zero", `rate(m[5m]) * 0`},
		{"metric plus zero", `up + 0`},
		{"metric pow zero", `up ^ 0`},
		{"metric pow one", `up ^ 1`},
		{"1 minus rate", `1 - rate(m[5m])`},
		{"100 minus percentage", `100 * (1 - rate(a[5m]) / rate(b[5m]))`},
		{"negative scalar", `up + -1`},
		{"double negation", `up - -1`},
		{"comparison then and", `up > 0 and rate(m[5m]) > 0`},
		{"multiple comparisons", `rate(a[5m]) > 0 and rate(b[5m]) < 100`},
		{"or with comparisons", `up == 0 or up == 1`},
		{"complex bool chain", `(up > bool 0) + (up < bool 2)`},
		{"nested arithmetic", `((rate(a[5m]) + 1) * 2 - 3) / 4`},
		{"binary of aggs", `sum(rate(a[5m])) / sum(rate(b[5m]))`},
		{"agg minus agg", `max(up) - min(up)`},
		{"agg plus scalar", `sum(rate(m[5m])) + 100`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 13: VECTOR MATCHING (561-620)
		// ═══════════════════════════════════════════════════════════════
		{"on() single label", `rate(a[5m]) / on (job) rate(b[5m])`},
		{"on() two labels", `rate(a[5m]) / on (job, instance) rate(b[5m])`},
		{"on() three labels", `rate(a[5m]) / on (job, instance, env) rate(b[5m])`},
		{"ignoring() single", `rate(a[5m]) / ignoring (instance) rate(b[5m])`},
		{"ignoring() two", `rate(a[5m]) / ignoring (instance, pod) rate(b[5m])`},
		{"on group_left empty", `rate(a[5m]) / on (job) group_left () rate(b[5m])`},
		{"on group_left 1 label", `rate(a[5m]) / on (job) group_left (version) build_info`},
		{"on group_left 2 labels", `rate(a[5m]) / on (job) group_left (version, build) build_info`},
		{"on group_right empty", `rate(a[5m]) * on (job) group_right () rate(b[5m])`},
		{"on group_right 1 label", `rate(a[5m]) * on (job) group_right (version) rate(b[5m])`},
		{"ignoring group_left", `rate(a[5m]) / ignoring (instance) group_left (version) build_info`},
		{"ignoring group_right", `rate(a[5m]) * ignoring (instance) group_right (extra) rate(b[5m])`},
		{"on + add", `rate(a[5m]) + on (job) rate(b[5m])`},
		{"on + sub", `rate(a[5m]) - on (job) rate(b[5m])`},
		{"on + mul", `rate(a[5m]) * on (job) rate(b[5m])`},
		{"on + pow", `rate(a[5m]) ^ on (job) rate(b[5m])`},
		{"on + comparison", `rate(a[5m]) > on (job) rate(b[5m])`},
		{"on + bool comparison", `rate(a[5m]) > bool on (job) rate(b[5m])`},
		{"agg on group_left", `sum by (job) (rate(a[5m])) / on (job) group_left (version) max by (job, version) (build_info)`},
		{"agg ignoring group_right", `sum by (instance) (rate(a[5m])) * ignoring (job) group_right () sum by (instance) (rate(b[5m]))`},
		{"complex vector match arithmetic", `(rate(a[5m]) * on(instance) group_left(role) node_info) / on(role) group_left() role_capacity`},
		{"nested on", `(rate(a[5m]) / on(job) rate(b[5m])) / on(job) rate(c[5m])`},
		{"binary both have matching", `rate(a[5m]) / on(job) group_left(v) b + on(job) rate(c[5m])`},
		// Logical operators with matching
		{"and plain", `up == 1 and rate(m[5m]) > 0`},
		{"or plain", `up == 0 or absent(up)`},
		{"unless plain", `rate(a[5m]) unless rate(b[5m])`},
		{"and on()", `up == 1 and on (job) rate(m[5m]) > 0`},
		{"or on()", `rate(a[5m]) or on(job) rate(b[5m])`},
		{"unless ignoring()", `rate(a[5m]) > 0.5 unless ignoring (instance) rate(b[5m]) > 0.1`},
		{"multi and", `up == 1 and rate(a[5m]) > 0 and rate(b[5m]) < 1`},
		{"multi or", `up == 0 or absent(up) or rate(m[5m]) > 100`},
		{"or then unless", `(up == 0 or absent(up)) unless on (job) (rate(m[5m]) > 0)`},
		{"and then or", `(up == 1 and rate(a[5m]) > 0) or (up == 0)`},
		{"unless then or", `(rate(a[5m]) unless rate(b[5m])) or rate(c[5m])`},
		{"complex and unless", `(rate(a[5m]) > 0 and rate(b[5m]) > 0) unless rate(c[5m]) > 100`},
		// More vector matching edge cases
		{"on ignoring mix", `rate(a[5m]) / on(job) rate(b[5m]) + ignoring(instance) rate(c[5m])`},
		{"on with sum", `sum by(job)(rate(a[5m])) / on(job) sum by(job)(rate(b[5m]))`},
		{"group_left with sum", `sum by(path,method)(rate(a[5m])) / on(path) group_left() sum by(path)(rate(b[5m]))`},
		{"ignoring with sum", `sum by(job)(rate(a[5m])) - ignoring(instance) sum by(job)(rate(b[5m]))`},
		{"bool with on", `rate(a[5m]) == bool on(job) rate(b[5m])`},
		{"unless ignoring multi", `rate(a[5m]) unless ignoring(instance, pod) rate(b[5m])`},
		{"on + and combo", `(rate(a[5m]) / on(job) rate(b[5m])) and (up == 1)`},
		{"complex nested matching", `sum by(job)(rate(a[5m]) / on(instance) group_left(role) node_roles)`},
		{"double division matching", `rate(a[5m]) / on(job) group_left() (rate(b[5m]) / on(job) rate(c[5m]))`},
		{"nested or with matching", `(up == 0 or on(job) absent(up)) unless rate(m[5m]) > 100`},
		{"ignoring group_left 2 labels", `rate(a[5m]) / ignoring(pod) group_left(node, zone) node_info`},
		{"on group_right 2 labels", `rate(a[5m]) * on(job) group_right(version, build) build_info`},
		{"on with max and group_left", `rate(a[5m]) / on(job) group_left(region) max by(job, region) (cluster_info)`},
		{"triple binary with matching", `rate(a[5m]) / on(job) rate(b[5m]) * on(job) rate(c[5m])`},
		{"unless with group_left context", `(rate(a[5m]) / on(job) group_left(v) build_info) unless rate(c[5m]) > 10`},
		{"4-way or", `up == 0 or absent(up) or rate(a[5m]) > 100 or rate(b[5m]) > 100`},
		{"and and and", `up == 1 and rate(a[5m]) > 0 and rate(b[5m]) > 0 and rate(c[5m]) > 0`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 14: UNARY OPERATIONS (621-640)
		// ═══════════════════════════════════════════════════════════════
		{"unary minus metric", `-up`},
		{"unary plus metric", `+up`},
		{"unary minus rate", `-rate(m[5m])`},
		{"unary plus rate", `+rate(m[5m])`},
		{"unary minus sum", `-sum(rate(m[5m]))`},
		{"unary minus in binary", `-rate(a[5m]) + rate(b[5m])`},
		{"double negation", `-(-rate(a[5m]))`},
		{"triple negation", `-(-(-(up)))`},
		{"unary in parens", `(-up) + 1`},
		{"unary minus scalar", `-1`},
		{"unary plus scalar", `+1`},
		{"unary minus in agg", `sum by (job) (-rate(m[5m]))`},
		{"unary in complex", `-(rate(a[5m]) - rate(b[5m]))`},
		{"unary minus of abs", `-(abs(delta(m[1h])))`},
		{"unary minus of sqrt", `-(sqrt(up))`},
		{"unary in comparison", `-up > -1`},
		{"unary with bool", `-up > bool 0`},
		{"unary of vector", `-vector(1)`},
		{"unary chain", `- - up`},
		{"unary of clamp", `-(clamp(up, 0, 1))`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 15: PARENTHESIZED EXPRESSIONS (641-660)
		// ═══════════════════════════════════════════════════════════════
		{"single parens", `(up)`},
		{"double parens", `((up))`},
		{"triple parens", `(((up)))`},
		{"deep parens", `(((((up)))))`},
		{"parens around binary", `(rate(a[5m]) + rate(b[5m]))`},
		{"parens in mul", `(rate(a[5m]) + 1) * 100`},
		{"nested parens binary", `((rate(a[5m]) + rate(b[5m])) * (rate(c[5m]) - rate(d[5m])))`},
		{"parens in agg", `sum by (job) ((rate(m[5m])))`},
		{"parens around comparison", `(up == 1) or (up == 0)`},
		{"parens in complex", `((up == 1) and (rate(m[5m]) > 0)) or (absent(up))`},
		{"parens around sum", `(sum(rate(m[5m]))) + 0`},
		{"parens around vector", `(vector(1))`},
		{"parens around scalar", `(scalar(sum(up)))`},
		{"parens around label_replace", `(label_replace(up, "a", "$1", "job", "(.*)"))`},
		{"parens in unless", `(rate(a[5m]) > 0) unless (rate(b[5m]) > 0)`},
		{"deeply nested mixed", `(((rate(a[5m]) + 1) * 2) - 3) / 4`},
		{"parens around sort", `(sort_desc(rate(m[5m])))`},
		{"parens in histogram", `histogram_quantile(0.99, sum by (le) (rate(bucket[5m])))`},
		{"parens around absent", `(absent(nonexistent))`},
		{"parens around clamp", `(clamp(rate(m[5m]), 0, 100))`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 16: SUBQUERIES (661-710)
		// ═══════════════════════════════════════════════════════════════
		{"subquery basic", `max_over_time(rate(m[5m])[30m:1m])`},
		{"subquery no step", `max_over_time(rate(m[5m])[30m:])`},
		{"subquery 1h:5m", `avg_over_time(rate(m[5m])[1h:5m])`},
		{"subquery 1d:1h", `max_over_time(rate(m[5m])[1d:1h])`},
		{"subquery with offset", `max_over_time(rate(m[5m])[1h:5m] offset 2h)`},
		{"subquery with @", `max_over_time(rate(m[5m])[1d:1h] @ 1609459200)`},
		{"subquery sum inner", `avg_over_time(sum(rate(m[5m]))[1h:5m])`},
		{"subquery avg inner", `max_over_time(avg by (job) (rate(m[5m]))[30m:1m])`},
		{"subquery min_over_time", `min_over_time(rate(m[5m])[30m:1m])`},
		{"subquery count_over_time", `count_over_time(rate(m[5m])[30m:1m])`},
		{"subquery stddev_over_time", `stddev_over_time(rate(m[5m])[1h:5m])`},
		{"subquery stdvar_over_time", `stdvar_over_time(rate(m[5m])[1h:5m])`},
		{"subquery quantile_over_time", `quantile_over_time(0.99, rate(m[5m])[1h:5m])`},
		{"subquery rate", `rate(max_over_time(m[1h])[10m:1m])`},
		{"subquery deriv", `deriv(rate(m[5m])[1h:1m])`},
		{"subquery predict_linear", `predict_linear(avg_over_time(m[30m])[2h:1m], 86400)`},
		{"subquery in binary", `rate(m[5m]) > avg_over_time(rate(m[5m])[1h:5m])`},
		{"subquery both sides", `max_over_time(rate(a[5m])[30m:1m]) / avg_over_time(rate(b[5m])[30m:1m])`},
		{"subquery in sum", `sum by (job) (max_over_time(rate(m[5m])[1h:5m]))`},
		{"subquery in topk", `topk(5, max_over_time(rate(m[5m])[1h:5m]))`},
		{"subquery in abs", `abs(avg_over_time(delta(m[5m])[1h:5m]))`},
		{"subquery in clamp", `clamp(max_over_time(rate(m[5m])[1h:5m]), 0, 100)`},
		{"subquery in label_replace", `label_replace(max_over_time(rate(m[5m])[1h:5m]), "svc", "$1", "job", "(.*)")`},
		{"subquery in sort", `sort_desc(max_over_time(rate(m[5m])[1h:5m]))`},
		{"subquery offset 1w", `avg_over_time(sum(rate(m[5m]))[1h:5m] offset 1w)`},
		{"subquery 2h:10m", `max_over_time(rate(m[5m])[2h:10m])`},
		{"subquery 4h:30m", `avg_over_time(rate(m[5m])[4h:30m])`},
		{"subquery chained", `avg_over_time(max_over_time(rate(m[5m])[30m:1m])[1h:5m])`},
		{"subquery in comparison", `max_over_time(rate(m[5m])[1h:5m]) > 1.0`},
		{"subquery in and", `max_over_time(rate(a[5m])[1h:5m]) > 0 and min_over_time(rate(b[5m])[1h:5m]) > 0`},
		{"subquery in unless", `max_over_time(rate(a[5m])[1h:5m]) unless min_over_time(rate(b[5m])[1h:5m])`},
		{"subquery in on", `max_over_time(rate(a[5m])[1h:5m]) / on(job) avg_over_time(rate(b[5m])[1h:5m])`},
		{"subquery of increase", `avg_over_time(increase(m[1h])[1d:1h])`},
		{"subquery of irate", `max_over_time(irate(m[5m])[30m:1m])`},
		{"subquery of delta", `avg_over_time(delta(m[1h])[1d:1h])`},
		{"subquery with label filter", `max_over_time(rate(m{job="api"}[5m])[1h:5m])`},
		{"subquery deep nesting", `sum(max_over_time(avg by(job)(rate(m[5m]))[1h:5m]))`},
		{"subquery of abs", `avg_over_time(abs(delta(m[1h]))[1d:1h])`},
		{"subquery of sqrt", `max_over_time(sqrt(rate(m[5m]))[30m:1m])`},
		{"subquery of sin", `avg_over_time(sin(rate(m[5m]))[1h:5m])`},
		{"subquery in histogram", `histogram_quantile(0.95, sum by(le)(max_over_time(rate(bucket[5m])[1h:5m])))`},
		{"subquery in 3-level", `max(sum by(job)(max_over_time(rate(m[5m])[1h:5m])))`},
		{"subquery quantile agg deep", `quantile(0.95, max_over_time(rate(m[5m])[1h:5m]))`},
		{"subquery in complex binary", `(max_over_time(rate(a[5m])[1h:5m]) + 1) * avg_over_time(rate(b[5m])[1h:5m])`},
		{"subquery with offset and labels", `max_over_time(rate(m{env="prod"}[5m])[1h:5m] offset 2h)`},
		{"subquery in or", `max_over_time(rate(a[5m])[1h:5m]) > 10 or min_over_time(rate(b[5m])[1h:5m]) < 0.1`},
		{"subquery of floor", `max_over_time(floor(rate(m[5m]))[1h:5m])`},
		{"subquery of ceil", `min_over_time(ceil(rate(m[5m]))[1h:5m])`},
		{"subquery of clamp_min", `avg_over_time(clamp_min(rate(m[5m]), 0)[1h:5m])`},
		{"subquery of clamp_max", `avg_over_time(clamp_max(rate(m[5m]), 100)[1h:5m])`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 17: LITERALS & EDGE CASES (711-750)
		// ═══════════════════════════════════════════════════════════════
		{"number int", `42`},
		{"number float", `3.14`},
		{"number zero", `0`},
		{"number negative", `-1`},
		{"number large", `1000000`},
		{"number small float", `0.001`},
		{"number scientific", `1e3`},
		{"number neg scientific", `1e-3`},
		{"string in label_replace", `label_replace(up, "dc", "us-east", "", "")`},
		{"comment handling", `up # this is a comment`},
		{"comment in middle", `rate(m[5m]) # compute the rate`},
		{"comment with metric", `http_requests_total{job="api"} # filter by job`},
		{"metric ending in _total", `http_requests_total`},
		{"metric ending in _count", `http_request_duration_seconds_count`},
		{"metric ending in _sum", `http_request_duration_seconds_sum`},
		{"metric ending in _bucket", `http_request_duration_seconds_bucket`},
		{"metric ending in _created", `http_request_duration_seconds_created`},
		{"metric ending in _info", `build_info`},
		{"process metric", `process_cpu_seconds_total`},
		{"node metric", `node_memory_MemTotal_bytes`},
		{"go runtime metric", `go_goroutines`},
		{"container metric", `container_memory_usage_bytes`},
		{"kube metric", `kube_pod_info`},
		{"all matchers combo", `m{a="x",b!="y",c=~"z.*",d!~"w.*"}`},
		{"empty result set", `absent(nonexistent_metric_that_does_not_exist)`},
		{"very long metric name", `very_long_metric_name_that_tests_identifier_parsing_limits_aaaaaaa`},
		{"unicode-safe label value", `m{label="value123"}`},
		{"numeric-looking label value", `m{code="200"}`},
		{"dot in label value", `m{version="1.2.3"}`},
		{"slash in label value", `m{path="/api/v1/query"}`},
		{"colon in label value", `m{instance="host:9090"}`},
		{"at sign in label value", `m{email="user@host.com"}`},
		{"space in label value", `m{msg="hello world"}`},
		{"equals in label value", `m{query="a=b"}`},
		{"empty label name metric", `{__name__="up"}`},
		{"regex alternation in value", `m{method=~"GET|POST|PUT|DELETE|PATCH"}`},
		{"regex dot star", `m{path=~".*"}`},
		{"regex caret", `m{path=~"^/api"}`},
		{"regex dollar", `m{path=~"/api$"}`},
		{"neg regex complex", `m{path!~"/health|/metrics|/ready"}`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 18: PRODUCTION SRE PATTERNS (751-850)
		// ═══════════════════════════════════════════════════════════════
		// Error rates
		{"SLA: error rate", `sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))`},
		{"SLA: 1 - error rate", `1 - (sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])))`},
		{"SLA: error rate by service", `sum by (job) (rate(http_requests_total{status=~"5.."}[5m])) / sum by (job) (rate(http_requests_total[5m]))`},
		{"SLA: error rate > 0.01", `sum by (job) (rate(http_requests_total{status=~"5.."}[5m])) / sum by (job) (rate(http_requests_total[5m])) > 0.01`},
		{"SLA: 99.9 availability", `(1 - (sum(rate(http_requests_total{status=~"5.."}[30m])) / sum(rate(http_requests_total[30m])))) * 100`},
		// Burn rates
		{"burn rate 1h", `sum(rate(http_requests_total{status=~"5.."}[1h])) / sum(rate(http_requests_total[1h]))`},
		{"burn rate 6h", `sum(rate(http_requests_total{status=~"5.."}[6h])) / sum(rate(http_requests_total[6h]))`},
		{"burn rate check", `(sum(rate(http_requests_total{status=~"5.."}[1h])) / sum(rate(http_requests_total[1h]))) > 14.4 * 0.001`},
		{"multi-window burn", `(sum(rate(http_requests_total{status=~"5.."}[1h])) / sum(rate(http_requests_total[1h]))) > (14.4 * 0.001) and (sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))) > (14.4 * 0.001)`},
		// Latency
		{"p50 latency", `histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"p95 latency", `histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"p99 latency", `histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"latency by path", `histogram_quantile(0.95, sum by (le, path) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"latency SLO violation", `histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket[5m]))) > 1.0`},
		// CPU
		{"CPU usage", `rate(process_cpu_seconds_total[5m])`},
		{"CPU avg by instance", `avg by (instance) (rate(node_cpu_seconds_total[5m]))`},
		{"CPU idle", `avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]))`},
		{"CPU saturation", `1 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]))`},
		{"CPU saturation > 90%", `(1 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) > 0.9`},
		// Memory
		{"memory usage bytes", `node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes`},
		{"memory usage percent", `(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100`},
		{"memory usage > 80%", `((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100) > 80`},
		// Disk
		{"disk space free", `node_filesystem_free_bytes`},
		{"disk space percent used", `(node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100`},
		{"disk fill prediction", `predict_linear(node_filesystem_free_bytes[4h], 86400) < 0`},
		{"disk fill prediction 4h", `predict_linear(node_filesystem_free_bytes[1h], 4*3600) < 0`},
		// Network
		{"network receive rate", `rate(node_network_receive_bytes_total[5m])`},
		{"network transmit rate", `rate(node_network_transmit_bytes_total[5m])`},
		{"network error rate", `rate(node_network_receive_errs_total[5m]) + rate(node_network_transmit_errs_total[5m])`},
		// K8s patterns
		{"pod memory vs limit", `sum by (pod) (container_memory_usage_bytes) / on(pod) group_left() sum by(pod) (kube_pod_container_resource_limits{resource="memory"})`},
		{"pod cpu vs request", `sum by (pod) (rate(container_cpu_usage_seconds_total[5m])) / on(pod) group_left() sum by(pod) (kube_pod_container_resource_requests{resource="cpu"})`},
		{"deployment replicas ready", `sum by (deployment) (kube_deployment_status_replicas_available) / sum by (deployment) (kube_deployment_spec_replicas)`},
		{"deployment not ready", `sum by (deployment) (kube_deployment_status_replicas_available) / sum by (deployment) (kube_deployment_spec_replicas) < 1`},
		{"OOM kills", `increase(kube_pod_container_status_terminated_reason{reason="OOMKilled"}[1h]) > 0`},
		{"pod restarts", `increase(kube_pod_container_status_restarts_total[1h]) > 3`},
		{"node not ready", `kube_node_status_condition{condition="Ready",status="true"} == 0`},
		{"pending pods", `kube_pod_status_phase{phase="Pending"} > 0`},
		// Anomaly detection patterns
		{"spike detection", `rate(http_requests_total[5m]) > 1.5 * rate(http_requests_total[5m] offset 1h)`},
		{"drop detection", `rate(http_requests_total[5m]) < 0.5 * rate(http_requests_total[5m] offset 1h)`},
		{"trend vs last week", `abs(rate(http_requests_total[1h]) - rate(http_requests_total[1h] offset 1w)) / rate(http_requests_total[1h] offset 1w)`},
		{"stddev band upper", `rate(m[5m]) > (avg(rate(m[5m])) + 2 * stddev(rate(m[5m])))`},
		{"stddev band lower", `rate(m[5m]) < (avg(rate(m[5m])) - 2 * stddev(rate(m[5m])))`},
		// Request patterns
		{"requests per second", `sum(rate(http_requests_total[5m]))`},
		{"requests per second by job", `sum by (job) (rate(http_requests_total[5m]))`},
		{"top 10 paths", `topk(10, sum by (path) (rate(http_requests_total[5m])))`},
		{"slow queries", `histogram_quantile(0.99, sum by (le, path) (rate(http_request_duration_seconds_bucket[5m]))) > 5`},
		// Multi-signal
		{"RED: rate", `sum(rate(http_requests_total[5m]))`},
		{"RED: errors", `sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))`},
		{"RED: duration", `histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"USE: utilization", `1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m]))`},
		{"USE: saturation", `avg(node_load1) / count(node_cpu_seconds_total{mode="idle"})`},
		{"USE: errors", `rate(node_network_receive_errs_total[5m])`},
		// Apdex
		{"apdex score", `(sum(rate(http_request_duration_seconds_bucket{le="0.5"}[5m])) + sum(rate(http_request_duration_seconds_bucket{le="2.0"}[5m]))) / 2 / sum(rate(http_request_duration_seconds_bucket{le="+Inf"}[5m]))`},
		// Capacity planning
		{"headroom cpu", `1 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])))`},
		{"headroom memory", `1 - (avg(node_memory_MemAvailable_bytes) / avg(node_memory_MemTotal_bytes))`},
		// Service dependencies
		{"svc dependency rate", `sum by (src_service, dst_service) (rate(rpc_calls_total[5m]))`},
		{"svc error rate", `sum by (src_service, dst_service) (rate(rpc_calls_total{status="error"}[5m])) / sum by (src_service, dst_service) (rate(rpc_calls_total[5m]))`},
		// Misc SRE
		{"up check", `up == 0`},
		{"instance down > 5min", `up == 0 and (time() - timestamp(up) > 300)`},
		{"absent check", `absent(up{job="critical-service"})`},
		{"changes detect restart", `changes(process_start_time_seconds[5m]) > 0`},
		{"predict disk full today", `predict_linear(node_filesystem_free_bytes[6h], 24*3600) < 0`},
		// Container patterns
		{"container cpu by namespace", `sum by (namespace) (rate(container_cpu_usage_seconds_total{image!=""}[5m]))`},
		{"container mem by namespace", `sum by (namespace) (container_memory_usage_bytes{image!=""})`},
		{"container throttled", `sum by (container) (rate(container_cpu_cfs_throttled_seconds_total[5m])) / sum by (container) (rate(container_cpu_usage_seconds_total[5m]))`},
		{"container network rx", `sum by (pod) (rate(container_network_receive_bytes_total[5m]))`},
		{"container network tx", `sum by (pod) (rate(container_network_transmit_bytes_total[5m]))`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 19: MEGA COMPLEX QUERIES (851-950)
		// ═══════════════════════════════════════════════════════════════
		{"mega: weighted error rate", `sum by (job) (rate(http_requests_total{status=~"5.."}[5m])) / on (job) group_left (version) sum by (job, version) (rate(http_requests_total[5m]))`},
		{"mega: latency+error combined", `histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket[5m]))) > 1 and sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.01`},
		{"mega: predict + rate compare", `predict_linear(node_filesystem_free_bytes[4h], 86400) < 0 and rate(node_disk_written_bytes_total[5m]) > 1e6`},
		{"mega: multi-signal alert", `(sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.01) or (histogram_quantile(0.99, sum by(le)(rate(http_request_duration_seconds_bucket[5m]))) > 2)`},
		{"mega: burn rate formula", `(sum(rate(http_requests_total{status=~"5.."}[1h])) / sum(rate(http_requests_total[1h]))) / 0.001`},
		{"mega: nested label ops", `label_join(label_replace(sum by (job) (rate(http_requests_total[5m])), "svc", "$1", "job", "(.*)"), "id", ":", "svc", "job")`},
		{"mega: histogram + vector match", `histogram_quantile(0.95, sum by (le, job) (rate(http_request_duration_seconds_bucket[5m]))) / on (job) group_left (version) max by (job, version) (build_info)`},
		{"mega: subquery + agg + binary", `sum by (job) (max_over_time(rate(http_requests_total[5m])[1h:5m])) / sum by (job) (avg_over_time(rate(http_requests_total[5m])[1h:5m]))`},
		{"mega: predict of smooth", `predict_linear(avg_over_time(node_filesystem_free_bytes[30m])[2h:1m], 86400) < 0`},
		{"mega: deriv of smooth", `deriv(avg_over_time(node_memory_MemAvailable_bytes[1h])[4h:1m]) < 0`},
		{"mega: ratio of subqueries", `max_over_time(rate(a[5m])[1h:5m]) / avg_over_time(rate(b[5m])[1h:5m])`},
		{"mega: 4-level agg", `max(sum by (cluster) (avg by (cluster, job) (sum by (cluster, job, instance) (rate(http_requests_total[5m])))))`},
		{"mega: complex clamped rate", `clamp(sum by (job) (rate(http_requests_total[5m])) * 100, 0, 10000)`},
		{"mega: error budget burn", `1 - (sum(rate(http_requests_total{status=~"5.."}[30m])) / sum(rate(http_requests_total[30m]))) / 0.0001`},
		{"mega: golden signal composite", `(sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))) + (histogram_quantile(0.99, sum by(le)(rate(http_request_duration_seconds_bucket[5m]))) / 10)`},
		{"mega: topk error paths", `topk(10, sum by (path, method) (rate(http_requests_total{status=~"5.."}[5m])) / sum by (path, method) (rate(http_requests_total[5m])))`},
		{"mega: absent with complex", `absent(up{job="critical"}) or (rate(http_requests_total{job="critical"}[5m]) == 0)`},
		{"mega: math chain", `sqrt(abs(sum(rate(http_requests_total[5m])) - avg(rate(http_requests_total[5m]))))`},
		{"mega: trig with time", `sin(time() / 86400 * pi()) * rate(http_requests_total[5m])`},
		{"mega: complex vector match chain", `(rate(a[5m]) / on(job) group_left(version) build_info) * on(version) group_left(region) version_config`},
		{"mega: nested sort label", `sort_desc(label_replace(sum by (job) (rate(http_requests_total[5m])), "svc", "$1", "job", "(.*)"))`},
		{"mega: histogram diff", `histogram_quantile(0.99, sum by(le)(rate(bucket[5m]))) - histogram_quantile(0.5, sum by(le)(rate(bucket[5m])))`},
		{"mega: floor of error rate", `floor(sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) * 10000) / 100`},
		{"mega: ceil of latency", `ceil(histogram_quantile(0.99, sum by(le)(rate(http_request_duration_seconds_bucket[5m]))) * 1000)`},
		{"mega: round percentage", `round(sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) * 100, 0.01)`},
		{"mega: log scale rate", `log10(sum(rate(http_requests_total[5m])) + 1)`},
		{"mega: exp decay", `exp(-rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]))`},
		{"mega: power law check", `rate(a[5m]) ^ 0.5 + rate(b[5m]) ^ 0.5`},
		{"mega: sgn of delta with agg", `sgn(sum(delta(temperature[1h])))`},
		{"mega: abs clamp round", `round(clamp(abs(delta(temperature[1h])), 0, 100), 0.1)`},
		{"mega: multi-label histogram", `histogram_quantile(0.95, sum by (le, job, path, method, status) (rate(http_request_duration_seconds_bucket[5m])))`},
		{"mega: nested unary", `-(-(-(sum(rate(m[5m])))))  `},
		{"mega: deep parens binary", `((((rate(a[5m]) + rate(b[5m])) * 2) - rate(c[5m])) / rate(d[5m]))`},
		{"mega: bool chain", `(up > bool 0) * (rate(m[5m]) > bool 0)`},
		{"mega: count_values + sort", `sort_desc(count_values("version", build_info))`},
		{"mega: topk of histogram", `topk(3, histogram_quantile(0.99, sum by(le, job)(rate(bucket[5m]))))`},
		{"mega: bottomk of error rate", `bottomk(5, sum by(job)(rate(http_requests_total{status=~"5.."}[5m])) / sum by(job)(rate(http_requests_total[5m])))`},
		{"mega: quantile of subquery", `quantile(0.95, max_over_time(rate(m[5m])[1h:5m]))`},
		{"mega: stddev of rate ratio", `stddev(sum by(job)(rate(a[5m])) / sum by(job)(rate(b[5m])))`},
		{"mega: complex unless", `(sum by(job)(rate(http_requests_total{status=~"5.."}[5m])) / sum by(job)(rate(http_requests_total[5m])) > 0.01) unless (sum by(job)(rate(http_requests_total[5m])) < 10)`},
		{"mega: sum of label_replace", `sum by (svc) (label_replace(rate(http_requests_total[5m]), "svc", "$1", "job", "(.*)"))`},
		{"mega: avg of label_join", `avg(label_join(up, "id", "-", "job", "instance"))`},
		{"mega: vector(0) or metric", `vector(0) or up`},
		{"mega: time based filter", `rate(http_requests_total[5m]) > 0 and time() - timestamp(http_requests_total) < 600`},
		{"mega: complex ratio with ceiling", `ceil(sum by(job)(rate(a[5m])) / on(job) group_left() sum by(job)(rate(b[5m])) * 100)`},
		{"mega: nested abs sgn", `abs(sgn(delta(temperature[1h])))`},
		{"mega: predict + sort", `sort_desc(predict_linear(node_filesystem_free_bytes[4h], 86400))`},
		{"mega: deriv in avg comparison", `avg by (instance) (deriv(node_filesystem_free_bytes[1h])) < -1e6`},
		{"mega: changes + resets sum", `sum by(job)(changes(process_start_time_seconds[1h])) + sum by(job)(resets(process_start_time_seconds[1h]))`},
		{"mega: complex multi-or", `up == 0 or absent(up{job="critical"}) or (rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05) or (histogram_quantile(0.99, sum by(le)(rate(http_request_duration_seconds_bucket[5m]))) > 5)`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 20: THE ULTIMATE MEGA QUERIES (951-1000)
		// ═══════════════════════════════════════════════════════════════
		{"ultimate: full SLO dashboard", `label_replace(sort_desc(sum by (job) (rate(http_requests_total{status=~"5.."}[5m])) / sum by (job) (rate(http_requests_total[5m]))), "svc", "$1", "job", "(.*)")`},
		{"ultimate: Apdex from histogram", `(sum(rate(http_request_duration_seconds_bucket{le="0.5"}[5m])) + sum(rate(http_request_duration_seconds_bucket{le="2.0"}[5m]))) / 2 / sum(rate(http_request_duration_seconds_bucket{le="+Inf"}[5m]))`},
		{"ultimate: weighted latency", `histogram_quantile(0.99, sum by (le, cluster) (rate(http_request_duration_seconds_bucket[5m]))) * on(cluster) group_left(region) max by(cluster, region)(cluster_weight)`},
		{"ultimate: memory leak detect", `deriv(avg_over_time(process_resident_memory_bytes[1h])[6h:5m]) > 0`},
		{"ultimate: disk + cpu alarm", `(predict_linear(node_filesystem_free_bytes[4h], 86400) < 0) or (1 - avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[5m])) > 0.9)`},
		{"ultimate: multi-window SLO", `((sum(rate(http_requests_total{status=~"5.."}[1h])) / sum(rate(http_requests_total[1h]))) > (14.4 * 0.001) and (sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))) > (14.4 * 0.001)) or ((sum(rate(http_requests_total{status=~"5.."}[6h])) / sum(rate(http_requests_total[6h]))) > (6 * 0.001) and (sum(rate(http_requests_total{status=~"5.."}[30m])) / sum(rate(http_requests_total[30m]))) > (6 * 0.001))`},
		{"ultimate: dashboard panel A", `round(clamp(sum by(job)(rate(http_requests_total[5m])) * 100 / on(job) group_left() max by(job)(http_server_max_requests), 0, 100), 0.1)`},
		{"ultimate: dashboard panel B", `label_replace(topk(10, sum by(path, method)(rate(http_requests_total{status=~"5.."}[5m])) / sum by(path, method)(rate(http_requests_total[5m]))), "endpoint", "$1 $2", "path", "(.*)")`},
		{"ultimate: complex subquery deriv", `sort_desc(predict_linear(deriv(process_resident_memory_bytes[1h])[2h:5m], 3600))`},
		{"ultimate: histogram label ops", `label_replace(histogram_quantile(0.95, sum by (le, path, method) (rate(http_request_duration_seconds_bucket{job=~"core-.*",status!~"5.."}[5m] offset 1h))), "service", "$1", "job", "(.*)-.*")`},
		{"ultimate: nested everything", `label_join(label_replace(sort_desc(sum by(job)(rate(http_requests_total[5m]))), "svc", "$1", "job", "(.*)"), "id", ":", "svc", "job")`},
		{"ultimate: floor ceil round combo", `floor(ceil(round(rate(m[5m]), 0.1)) / 10) * 10`},
		{"ultimate: trig chain", `asin(sin(rate(m[5m]) * 0)) + acos(cos(rate(m[5m]) * 0))`},
		{"ultimate: exp ln round trip", `round(exp(ln(abs(rate(m[5m])) + 1)) - 1, 0.001)`},
		{"ultimate: all math funcs", `abs(ceil(floor(round(sqrt(ln(exp(sgn(rate(m[5m])))))))))  `},
		{"ultimate: deep agg chain", `topk(5, sum by(job)(avg by(job, instance)(max by(job, instance, pod)(rate(container_cpu_usage_seconds_total[5m])))))`},
		{"ultimate: 5-way or alert", `up == 0 or absent(up{job="critical"}) or (rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05) or (histogram_quantile(0.99, sum by(le)(rate(http_request_duration_seconds_bucket[5m]))) > 5) or (predict_linear(node_filesystem_free_bytes[4h], 86400) < 0)`},
		{"ultimate: triple vector match", `(rate(a[5m]) / on(job) group_left(v) build_info) * on(v) group_left(region) version_regions / on(region) group_left() region_capacity`},
		{"ultimate: nested subquery agg", `sum(max_over_time(avg by(job)(rate(http_requests_total[5m]))[1h:5m]))`},
		{"ultimate: complex clamp chain", `clamp_max(clamp_min(sum by(job)(rate(http_requests_total[5m])), 0), 1000)`},
		{"ultimate: rate of rate proxy", `avg_over_time(rate(http_requests_total[5m])[30m:5m])`},
		{"ultimate: histogram + unless", `(histogram_quantile(0.99, sum by(le, job)(rate(bucket[5m]))) > 2) unless (sum by(job)(rate(http_requests_total[5m])) < 1)`},
		{"ultimate: multi-level label", `label_replace(label_replace(label_replace(up, "a", "$1", "job", "(.*)"), "b", "$1", "instance", "(.*)"), "c", "$1", "a", "(.*)")`},
		{"ultimate: complex absent or", `absent(up{job="svc-a"}) or absent(up{job="svc-b"}) or absent(up{job="svc-c"})`},
		{"ultimate: predict of deriv subq", `predict_linear(deriv(process_cpu_seconds_total[1h])[4h:5m], 86400)`},
		{"ultimate: mixed subq + match", `max_over_time(rate(a[5m])[1h:5m] offset 1h) / on(job) group_left(v) avg_over_time(rate(b[5m])[1h:5m])`},
		{"ultimate: full combo 1", `label_replace(ceil(histogram_quantile(0.99, sum by(le, job)(rate(http_request_duration_seconds_bucket[5m]))) * 1000), "svc", "$1", "job", "(.*)")`},
		{"ultimate: full combo 2", `sort_desc(round(sum by(job)(rate(http_requests_total{status=~"5.."}[5m])) / sum by(job)(rate(http_requests_total[5m])) * 100, 0.01))`},
		{"ultimate: the kitchen sink", `label_join(label_replace(sort_desc((histogram_quantile(0.99,sum by(le,cluster)(rate(http_request_duration_seconds_bucket{method=~"PO.*|PU.*",status!="200"}[5m]offset 1d)))^(max_over_time(deriv(process_cpu_seconds_total[1h]@1700000000)[2h:1m])/on(cluster)group_left(version,build)count_values("version",build_info)))or(clamp((abs(idelta(kafka_topic_partition_current_offset[5m]))+scalar(round(vector(10.5))))%2,0,10)>bool 1)unless ignoring(instance,pod)((sin(time())*day_of_month())>0 and(changes(process_start_time_seconds[15m])+predict_linear(node_filesystem_free_bytes[1h],3600))>=0)),"source","$1","job","(.*)"),"final_label",",","source","version")`},
		{"ultimate: 7-deep nesting", `max(sum by(a)(avg by(a,b)(min by(a,b,c)(topk(10, sum by(a,b,c,d)(rate(m[5m])))))))`},
		{"ultimate: subquery chain deep", `avg_over_time(max_over_time(rate(m[5m])[30m:1m])[1h:5m])`},
		{"ultimate: bool arithmetic", `(up > bool 0) * (rate(m[5m]) > bool 0) * (1 - (rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])))`},
		{"ultimate: everything at once", `label_replace(clamp(sum by(job)(rate(http_requests_total{status=~"2.."}[5m] offset 1h)) / on(job) group_left(version) max by(job, version)(build_info), 0, 100), "svc", "$1", "job", "(.*)")`},
		{"ultimate: multi-service health", `(sum by(job)(rate(http_requests_total{status=~"5.."}[5m])) / sum by(job)(rate(http_requests_total[5m])) < 0.001) and (histogram_quantile(0.95, sum by(le, job)(rate(http_request_duration_seconds_bucket[5m]))) < 0.5) and (sum by(job)(up) > 0)`},
		{"ultimate: cascading thresholds", `(rate(m[5m]) > 100) or ((rate(m[5m]) > 50) and (rate(m[5m]) < 100) and (time() - timestamp(m) < 300))`},
		{"ultimate: resource efficiency", `(sum by(ns)(rate(container_cpu_usage_seconds_total[5m])) / sum by(ns)(kube_pod_container_resource_requests{resource="cpu"})) / on(ns) group_left() (sum by(ns)(container_memory_usage_bytes) / sum by(ns)(kube_pod_container_resource_requests{resource="memory"}))`},
		{"ultimate: cost attribution", `sum by(namespace)(rate(container_cpu_usage_seconds_total[5m])) * 0.03 + sum by(namespace)(container_memory_usage_bytes) / 1e9 * 0.004`},
		{"ultimate: anomaly composite", `(abs(rate(m[5m]) - avg(rate(m[5m]))) / stddev(rate(m[5m])) > 3) and (rate(m[5m]) > avg_over_time(rate(m[5m])[1h:5m]) * 1.5)`},
		{"ultimate: final boss", `label_join(label_replace(sort_desc(clamp(sum by(job)(rate(http_requests_total{status=~"5.."}[5m] offset 1h)) / on(job) group_left(version) max by(job, version)(build_info) * 100, 0, 100)), "svc", "$1", "job", "(.*)"), "uid", ":", "svc", "version")`},

		// ═══════════════════════════════════════════════════════════════
		// SECTION 21: ADDITIONAL COVERAGE TO REACH 1000 (882-1000)
		// ═══════════════════════════════════════════════════════════════
		// More matcher edge cases
		{"extra: 5 matchers", `m{a="1",b!="2",c=~"3.*",d!~"4.*",e="5"}`},
		{"extra: all eq matchers", `m{a="1",b="2",c="3",d="4",e="5",f="6"}`},
		{"extra: all neq matchers", `m{a!="1",b!="2",c!="3"}`},
		{"extra: all regex matchers", `m{a=~"1.*",b=~"2.*",c=~"3.*"}`},
		{"extra: all neg regex matchers", `m{a!~"1.*",b!~"2.*",c!~"3.*"}`},
		{"extra: name selector + matchers", `{__name__=~"http_.*",job="api",status!="500"}`},
		// More duration edge cases
		{"extra: range 45s", `m[45s]`},
		{"extra: range 90s", `m[90s]`},
		{"extra: range 3m", `m[3m]`},
		{"extra: range 10m", `m[10m]`},
		{"extra: range 20m", `m[20m]`},
		{"extra: range 45m", `m[45m]`},
		{"extra: range 3h", `m[3h]`},
		{"extra: range 6h", `m[6h]`},
		{"extra: range 12h", `m[12h]`},
		{"extra: range 2d", `m[2d]`},
		{"extra: range 3d", `m[3d]`},
		// More rate edge cases
		{"extra: rate 45s", `rate(m[45s])`},
		{"extra: rate 90s", `rate(m[90s])`},
		{"extra: rate 3m", `rate(m[3m])`},
		{"extra: rate 10m", `rate(m[10m])`},
		{"extra: rate 20m", `rate(m[20m])`},
		{"extra: rate 2h", `rate(m[2h])`},
		// More over-time edge cases
		{"extra: avg_over_time 15m", `avg_over_time(m[15m])`},
		{"extra: avg_over_time 2h", `avg_over_time(m[2h])`},
		{"extra: sum_over_time 30m", `sum_over_time(m[30m])`},
		{"extra: min_over_time 15m", `min_over_time(m[15m])`},
		{"extra: max_over_time 2h", `max_over_time(m[2h])`},
		{"extra: count_over_time 30m", `count_over_time(m[30m])`},
		// More aggregation combos
		{"extra: sum of floor", `sum(floor(rate(m[5m])))`},
		{"extra: avg of ceil", `avg(ceil(rate(m[5m])))`},
		{"extra: max of abs", `max(abs(delta(m[1h])))`},
		{"extra: min of sqrt", `min(sqrt(rate(m[5m])))`},
		{"extra: count of sgn", `count(sgn(delta(m[1h])))`},
		{"extra: sum of round", `sum(round(rate(m[5m]), 0.01))`},
		{"extra: sum of exp", `sum(exp(rate(m[5m])))`},
		{"extra: avg of ln", `avg(ln(rate(m[5m])))`},
		{"extra: max of log2", `max(log2(rate(m[5m])))`},
		{"extra: min of log10", `min(log10(rate(m[5m])))`},
		// More binary combos
		{"extra: 3-way add", `rate(a[5m]) + rate(b[5m]) + rate(c[5m])`},
		{"extra: 3-way mul", `rate(a[5m]) * rate(b[5m]) * rate(c[5m])`},
		{"extra: add then div", `(rate(a[5m]) + rate(b[5m])) / rate(c[5m])`},
		{"extra: sub then mul", `(rate(a[5m]) - rate(b[5m])) * rate(c[5m])`},
		{"extra: pow then add", `rate(a[5m]) ^ 2 + rate(b[5m]) ^ 2`},
		{"extra: complex arithmetic 2", `(rate(a[5m]) * 100 + rate(b[5m]) * 200) / (rate(c[5m]) + 1)`},
		{"extra: division chain", `rate(a[5m]) / rate(b[5m]) / rate(c[5m])`},
		{"extra: subtraction chain", `rate(a[5m]) - rate(b[5m]) - rate(c[5m])`},
		// More comparison combos
		{"extra: lt then and", `rate(a[5m]) < 0.5 and rate(b[5m]) > 0.1`},
		{"extra: gte then or", `rate(a[5m]) >= 1 or rate(b[5m]) <= 0`},
		{"extra: eq then unless", `up == 1 unless absent(up)`},
		{"extra: neq chained or", `up != 0 or up != 1`},
		{"extra: comparison chain", `rate(a[5m]) > 0 and rate(a[5m]) < 100`},
		// More vector matching combos
		{"extra: on 4 labels", `rate(a[5m]) / on(job, instance, env, dc) rate(b[5m])`},
		{"extra: ignoring 3 labels", `rate(a[5m]) / ignoring(instance, pod, container) rate(b[5m])`},
		{"extra: group_left 3 labels", `rate(a[5m]) / on(job) group_left(version, build, region) build_info`},
		{"extra: group_right 2 labels", `rate(a[5m]) * on(job) group_right(env, dc) rate(b[5m])`},
		// More subquery combos
		{"extra: subquery 10m:1m", `avg_over_time(rate(m[5m])[10m:1m])`},
		{"extra: subquery 20m:2m", `max_over_time(rate(m[5m])[20m:2m])`},
		{"extra: subquery 2h:15m", `avg_over_time(rate(m[5m])[2h:15m])`},
		{"extra: subquery 6h:30m", `max_over_time(rate(m[5m])[6h:30m])`},
		{"extra: subquery 1d:6h", `avg_over_time(rate(m[5m])[1d:6h])`},
		// More deriv/predict combos
		{"extra: deriv 30m", `deriv(m[30m])`},
		{"extra: deriv 2h", `deriv(m[2h])`},
		{"extra: deriv with labels", `deriv(m{env="prod"}[1h])`},
		{"extra: predict 1h ahead", `predict_linear(m[1h], 3600)`},
		{"extra: predict 4h ahead", `predict_linear(m[4h], 14400)`},
		{"extra: predict 1d ahead", `predict_linear(m[6h], 86400)`},
		// More label_replace patterns
		{"extra: label_replace no match regex", `label_replace(up, "x", "default", "nonexistent", "(.*)")`},
		{"extra: label_replace dot regex", `label_replace(up, "first", "$1", "instance", "([^.]+).*")`},
		{"extra: label_replace underscore sep", `label_replace(up, "a_b", "$1_$2", "instance", "(.+):(.+)")`},
		// More comment patterns
		{"extra: comment only whitespace before", `  up   # trailing comment`},
		{"extra: comment after rate", `rate(m[5m])  # compute rate  `},
		{"extra: comment after complex", `sum by(job)(rate(m[5m])) # per-job rate`},
		// More sort combos
		{"extra: sort of min", `sort(min by(job)(up))`},
		{"extra: sort of topk", `sort(topk(5, rate(m[5m])))`},
		{"extra: sort_desc of bottomk", `sort_desc(bottomk(5, up))`},
		{"extra: sort of histogram", `sort(histogram_quantile(0.99, sum by(le, job)(rate(bucket[5m]))))`},
		// More absent combos
		{"extra: absent with neq", `absent(m{job!="prod"})`},
		{"extra: absent with regex", `absent(m{job=~"test.*"})`},
		{"extra: absent of complex", `absent(http_requests_total{job="missing",env="prod",dc="us-east"})`},
		// More changes/resets combos
		{"extra: changes 5m", `changes(m[5m])`},
		{"extra: changes 1d", `changes(m[1d])`},
		{"extra: resets 5m", `resets(m[5m])`},
		{"extra: resets 1d", `resets(m[1d])`},
		{"extra: changes vs resets", `changes(m[1h]) - resets(m[1h])`},
		// More holt_winters
		{"extra: holt low smoothing", `holt_winters(m[1h], 0.1, 0.1)`},
		{"extra: holt high smoothing", `holt_winters(m[1h], 0.9, 0.9)`},
		{"extra: holt mixed params", `holt_winters(m[2h], 0.3, 0.7)`},
		// More scalar/vector combos
		{"extra: vector 100", `vector(100)`},
		{"extra: vector negative", `vector(-5)`},
		{"extra: vector float", `vector(0.001)`},
		{"extra: scalar of max", `scalar(max(up))`},
		{"extra: scalar of count", `scalar(count(up))`},
		{"extra: vector in comparison", `vector(0) < rate(m[5m])`},
		// More @ modifier combos
		{"extra: @ on instant", `up @ 1700000000`},
		{"extra: @ with neq", `up{job!="test"} @ 1700000000`},
		{"extra: @ with regex", `up{job=~"prod.*"} @ 1700000000`},
		{"extra: @ in rate", `rate(m[5m] @ 1609459200)`},
		{"extra: @ in increase", `increase(m[1h] @ 1609459200)`},
		{"extra: @ in avg_over_time", `avg_over_time(m[5m] @ 1609459200)`},
		// More offset combos
		{"extra: offset in sum", `sum(rate(m[5m] offset 2h))`},
		{"extra: offset in avg", `avg by(job)(rate(m[5m] offset 1d))`},
		{"extra: offset in max_over_time", `max_over_time(m[1h] offset 1w)`},
		{"extra: offset in delta", `delta(m[1h] offset 3h)`},
		{"extra: offset in deriv", `deriv(m[1h] offset 2h)`},
		// More complex production patterns
		{"extra: error budget remaining", `1 - sum(increase(http_requests_total{status=~"5.."}[24h])) / (sum(increase(http_requests_total[24h])) * 0.001)`},
		{"extra: saturation index", `(sum by(instance)(rate(node_cpu_seconds_total{mode!="idle"}[5m])) / sum by(instance)(rate(node_cpu_seconds_total[5m]))) * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))`},
		{"extra: request error ratio", `sum by(path)(rate(http_requests_total{status=~"5.."}[5m])) / (sum by(path)(rate(http_requests_total[5m])) + 1)`},
		{"extra: container cpu pct", `sum by(container)(rate(container_cpu_usage_seconds_total[5m])) * 100`},
		{"extra: pod memory pct", `sum by(pod)(container_memory_usage_bytes) / on(pod) group_left() sum by(pod)(kube_pod_container_resource_limits{resource="memory"}) * 100`},
		{"extra: network throughput", `sum by(instance)(rate(node_network_receive_bytes_total[5m]) + rate(node_network_transmit_bytes_total[5m]))`},
		{"extra: go alloc rate", `rate(go_memstats_alloc_bytes_total[5m])`},
		{"extra: go gc pause avg", `avg_over_time(go_gc_duration_seconds[5m])`},
		{"extra: process fd usage pct", `process_open_fds / process_max_fds * 100`},
		{"extra: coredns latency", `histogram_quantile(0.99, sum by(le)(rate(coredns_dns_request_duration_seconds_bucket[5m])))`},
		{"extra: etcd leader changes", `increase(etcd_server_leader_changes_seen_total[1h])`},
		{"extra: apiserver latency", `histogram_quantile(0.99, sum by(le, verb)(rate(apiserver_request_duration_seconds_bucket[5m])))`},
		{"extra: node load vs cpus", `node_load1 / count without(cpu, mode)(node_cpu_seconds_total{mode="idle"})`},
		{"extra: the 1000th query", `label_replace(sort_desc(topk(10, sum by(job)(rate(http_requests_total{status=~"5.."}[5m])) / on(job) group_left(version) max by(job,version)(build_info))), "svc", "$1", "job", "(.*)")`},
	}

	config := &transpiler.Config{
		Schema:             clickhouse.DefaultSchema(),
		EnableOptimization: true,
	}

	start, _ := time.Parse(time.RFC3339, "2024-01-01T00:00:00Z")
	end, _ := time.Parse(time.RFC3339, "2024-01-01T23:59:59Z")

	passed := 0
	failed := 0
	var failures []string

	for i, q := range queries {
		t := transpiler.New(config)
		t.SetTimeRange(start, end, 15*time.Second)

		_, err := t.Transpile(q.promql)
		if err != nil {
			failed++
			failures = append(failures, fmt.Sprintf("  [%03d] %-45s  FAIL: %v", i+1, q.name, err))
		} else {
			passed++
		}
	}

	fmt.Printf("\n══════════════════════════════════════════════\n")
	fmt.Printf("  PromQL 1000-Query Exhaustive Test\n")
	fmt.Printf("══════════════════════════════════════════════\n")
	fmt.Printf("  Total:  %d\n", len(queries))
	fmt.Printf("  Passed: %d\n", passed)
	fmt.Printf("  Failed: %d\n", failed)
	fmt.Printf("══════════════════════════════════════════════\n")

	if failed > 0 {
		fmt.Println("\nFailures:")
		for _, f := range failures {
			fmt.Println(f)
		}
		os.Exit(1)
	}
	fmt.Println("\n  ✅ ALL 1000 QUERIES PASSED!")
}
